SCREEN_WIDTH: int = 1280
SCREEN_HEIGHT: int = 720

PLAYER_RADIUS: int = 20
LINE_WIDTH: int = 2
PLAYER_TURN_SPEED: int = 300
PLAYER_SPEED: int = 200

ASTEROID_MIN_RADIUS: int = 20
ASTEROID_KINDS: int = 3
ASTEROID_SPAWN_RATE_SECONDS: float = 0.8
ASTEROID_MAX_RADIUS: int = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
